### ISSUE TITLE
"did you forget to ‘#include <memory>’" when building crazyswarm in Arch Linux

### ISSUE THREAD

**Issue by schlagenhauf** [USC-ACTLab/libmotioncapture#12]
Building crazyswarm in Arch Linux with `bash build.sh` produces

```
/home/pntagrl/repos/ext/crazyswarm/ros_ws/src/crazyswarm/externalDependencies/libmotioncapture/src/vrpn.cpp:11:1: note: ‘std::shared_ptr’ is defined in header ‘<memory>’; did you forget to ‘#include <memory>’?
   10 | #include <vrpn_Connection.h>
  +++ |+#include <memory>
```

Doing said include fixes the build.

gcc version: 11.1.0
cmake version: 3.22.0

This is basically the same as  USC-ACTLab/libobjecttracker#2

**Comment by whoenig** [comment]
This repo is actually deprecated (I'll mark it as such shortly). The newest version is available at https://github.com/IMRCLab/libmotioncapture. Could you comment at that repo in https://github.com/IMRCLab/libmotioncapture/issues/2 if you are still seeing the same or more issues there?
Thanks for the bug report and your help.
