### ISSUE TITLE
not backward compatible with Motive v.1.8.0 / NatNet v.2.8

### ISSUE THREAD

**Issue by jungr-ait** [USC-ACTLab/libmotioncapture#6]
Hello,

I think this commit https://github.com/USC-ACTLab/libmotioncapture/commit/ab26fd9fcccb25d513af218c95eb74a86dc131f9 is not backward compatible with Motive 1.8.0/NatNet Streaming Module v.2.8

Running the mocap_helper of the latest crazyswarm version with the prints enabled within the optitrack.cpp gives:

process[mocap_helper-2]: started with pid [6445]
frame 0:
got major/minor: 2.8
Message ID : 7
Byte count : 166
Frame # : 499054
Marker Set Count : 1
Unidentified Marker Count : -1097420973
[mocap_helper-2] process has died [pid 6445, exit code -11, cmd /crazyswarm/ros_ws/devel/lib/crazyswarm/mocap_helper __name:=mocap_helper __log:=/root/.ros/log/63eda72a-a493-11e9-bc6c-a44cc8597ee6/mocap_helper-2.log].
log file: /root/.ros/log/63eda72a-a493-11e9-bc6c-a44cc8597ee6/mocap_helper-2*.log

I will look for the latest NatNet protocol specification and see how to fix it. 

The parsed value for nOtherMarkers is negative (Unidentified Marker Count : -1097420973) and way bigger then the byte count of the packet received. So a sanity check could help here.

**Comment by whoenig** [comment]
I suggest you try https://github.com/whoenig/NatNetSDKCrossplatform and see if the problem persists (this is based on the official code using SDK 3.1).

**Comment by jungr-ait** [comment]
Hello,

got it working. I could successfully run the "hover_swarm.launch" and the "niceHover.py" in Optitrack using Motive 1.8, and Ubuntu16.04 on the host machine.
The configuration in the hover_swarm.launch is:
```
      ....
      motion_capture_type: "optitrack" # one of none,vicon,optitrack,qualisys,vrpn
      object_tracking_type: "libobjecttracker" # one of motionCapture,libobjecttracker
      vicon_host_name: "vicon"
      optitrack_host_name: "optitrack"
```
The hostname for optitrack was set in the /etc/hosts file
```
cat /etc/hosts
127.0.0.1	localhost
192.168.1.100   optitrack
```

The output of the hover_swarm.launch was:
```
Frame # : 236643
Marker Set Count : 1
marker name: all
Number of markers in set: 0
Unidentified Marker Count : 9
Rigid Body Count : 0
Skeleton Count : 0
Labeled Marker Count : 0
Message ID : 7
Byte count : 166
Frame # : 236644
Marker Set Count : 1
marker name: all
Number of markers in set: 0
Unidentified Marker Count : 9
Rigid Body Count : 0
Skeleton Count : 0
Labeled Marker Count : 0
```

## Now to my changes and questions
Changes in optitrack.cpp: 
- The problem was in the method MotionCaptureOptitrack::waitForNextFrame().
The markersets where not parsed according to the protocol definition of NatNetSDK 2.8 or NatNetSDK 3.1
The number of markers within a marker set was not considered. Also the function `strlen` returns a size_t, which could cause in extreme cases a negative integer value when casted to an integer. 
- Furthermore the markers of both the MarkerSets and OtherMarkers where not inserted in the makers vector, just the labeled markers. 
- My question is why? AFAIK/Guess  the pose of the CFs is estimited by a PCL matching of the specified markerConfigurations in crazyfieTypes. Thus, the algorithm does not make use of label ID. It just uses the position of each marker. In order to backward compatible, I added all markers to the markers vector by a push_back. The performance should not be a issue here. The vector needs to be cleared at the beginning of the function when a data frame was received.
- How was this code tested and did it really work? Unfortunately testing the library requires a running motion capture system. Maybe for the future a short dataset N-raw data arrays would be great. Then the parsing part needs to moved into a method and it could be proofed against the expectations.

## Suggestions
- parsing a frame by incremting a ptr is a bit risky. Especially when, like in this case, the size of the datatypes is not specified explicitly (I mean by using datatypes such as Exact-Width Floating-Point types or integer types, uint32_t, uint64_t) This fault comes also from the NatNetTypes definition. I have the impression they tried to be more precisely concerning this manner in the past releases..
- I would increment an index as one can compare it against the length of the buffer.  
- Another minus in the NatNetTypes.h definition: I would expect a member of a struct defined as char mName[MAX_LENGTH] to have always the length of MAX_LENGTH. Also when I received the data. Ofc this would be waste of bandwidth when the actual data is shorter. But treating this buffer as string is also hackish and dangerous. Image a singe bit flip in the string the delimiter... but the NatNet protocol definition is not our topic here...      
- For the uncommented printfs, one could use a marko/compile definition. 

KR

**Comment by jungr-ait** [comment]
Thank you for the link. It seems as if we wrote simultaneously :) I will now clean up my hack an commit it. It think an integration in the official code requires some testing. Unfortunately I cannot do it for other Motive Versions.

KR, Roland

**Comment by whoenig** [comment]
I tried to keep the code as close as possible to the official SDK to simplify upgrading to newer versions in the future. I do agree with most of your concerns, but this is the coding style the SDK is using. While it might be nice fixing those issues, this will make it much harder to upgrade to newer SDKs.

The code is actively tested and used using an OptiTrack motion capture system with Motive 2.0.

A PR is welcome of course, but I prefer if it just addresses the actual bug you are having with your Motive version. I can test with Motive 2.0.

Thanks for reporting and fixing!
Wolfgang

**Comment by jungr-ait** [comment]
Actually the bug was not in the Motive Version or the NatNet protocol. Parsing the data frame causes the issue. More precisely A) parsing issue in the MarkersSets B) Marker data were not added to the resulting marker vector.

The question concerning B) is still open. So if I am migration to Motive 2.0, should I stream different markers to my host PC? Ones with labels?  
KR

**Comment by whoenig** [comment]
Perhaps Motive 2.0 sends the data with a different encoding, so that the bug was not apparent. I am not entirely sure how OptiTrack distinguishes between labeled markers and unlabeled markers. I essentially disable any Assets in Motive (such that only markers are available, but Motive is not tracking any objects). The markers we are interested in are such free/unlabeled markers for custom tracking using ICP.
NaturalPoint also sells "active IR markers" now, but I am not sure how they would show up in the data stream.

**Comment by jungr-ait** [comment]
According to that information, Motive 2.0 is sending labeled markers, otherwise the code could not have worked for you. In Motive1.8 I could not see the option to specify labels for markers, but I did no investigations...

**Comment by whoenig** [comment]
Optitrack support has been improved in https://github.com/IMRCLab/libmotioncapture.
